import {
    Loader2,
    Github,
    Chrome,
    Command,
    ArrowRight,
    TrendingUp,
    MapPin,
    Check,
    AlertTriangle,
    Search,
    CreditCard,
    Plus,
    Store,
    MessageSquare,
    Star,
    Activity,
    ChevronLeft,
    Globe,
    Trophy,
    User,
    Bot,
    Smile,
    Minus,
    Skull,
    AlertCircle,
    CheckCircle,
    Settings,
    LogOut,
    FileDown,
    FileText
} from "lucide-react"

export const Icons = {
    spinner: Loader2,
    gitHub: Github,
    google: Chrome,
    logo: Command,
    arrowRight: ArrowRight,
    trending: TrendingUp,
    mapPin: MapPin,
    check: Check,
    warning: AlertTriangle,
    search: Search,
    creditCard: CreditCard,
    plus: Plus,
    store: Store,
    messageSquare: MessageSquare,
    star: Star,
    activity: Activity,
    chevronLeft: ChevronLeft,
    globe: Globe,
    trophy: Trophy,
    user: User,
    bot: Bot,
    smile: Smile,
    minus: Minus,
    skull: Skull,
    alertCircle: AlertCircle,
    checkCircle: CheckCircle,
    settings: Settings,
    logOut: LogOut,
    fileDown: FileDown,
    fileText: FileText
}
